pyeong777/orange-market

css/modifyProfile.css, pages/modifyProfile.html
=> 프로필 수정 페이지 추가

css/addProduct.css, pages/addProduct.html
=> 상품 등록 페이지 추가

css/addProduct.css, css/followList.css, css/modifyProfile.css, css/profile.css, pages/addProduct.html, pages/followList.html, pages/modifyProfile.html, pages/profile.html
1. 문서 전체를 div로 감싸는 방식으로 수정
2. 클래스명 및 UI 버그 수정
3. 하단에 nav 추가
=> 프로필, 팔로우, 프로필 수정, 상품 등록 페이지 UI 완성

css/postpage.css, js/postpage.js, pages/postpage.html
=> :memo: Add postpage.js and Fix postpage Markup

js/postpage.js
=> :white_check_mark: comment-btn fix

css/profile.css, js/profile.js, pages/profile.html
일부 모달과 버튼을 제외한 프로필 페이지 기능 구현
1. 현 페이지에서 API를 활용하기 위해 임시로 로그인 구현
2. 현재 프로필 화면이 내 화면인지 다른 유저 화면인지 구분하여 버튼 표시
3. 상품 목록 표시
4. 피드 목록 표시(목록형, 앨범형)
=> 프로필 페이지 기능 구현

css/joinMembership.css, css/joinMembership2.css, js/joinMembership.js, js/joinMembership2.js, js/loginEmail.js, pages/joinMembership.html, pages/joinMembership2.html, pages/loginEmail.html
Fix loginEmailPage html, js
Fix joinMembershipPage html, css, js
Fix joinMembership2Page html, css, js
=> Fix loginPage & joinPage html, css, js

css/profile.css, js/followList.js, js/profile.js, js/util.js, pages/followList.html
1. 팔로워/팔로잉 목록 페이지 추가
2. util함수의 goBack, gotoPage 함수 리팩토링
(로컬 스토리지의 prev에 객체를 stringify하여 저장하고, 이 값을 이용하여 이전 페이지의 로컬 스토리지 상태를 기록함.
뒤로 가기 버튼을 눌렀을 때 prev를 이용하여 이전 상태로 되돌릴 수 있음.)
=> 팔로워/팔로잉 목록 페이지 추가 및 util 함수 수정

css/profile.css, js/profile.js, js/util.js
1. toggleHeart가 제대로 동작하지 않는 버그 수정
2. 문서 전체의 가로 길이가 늘어나는 현상 수정
3. util.js의 gotoPage 함수의 기본 매개변수 지정
4. util.js에 이미지 가로 스크롤 함수 추가
=> 프로필 페이지 수정

css/joinMembership.css, css/joinMembership2.css, js/joinMembership.js, js/joinMembership2.js, js/loginEmail.js
Fix loginPage js
Fix joinMembershipPage js
Fix joinMembership2Page js
유효성 검사 js 수정
=> Fix Feature/loginPage & joinPage js files

css/postpage.css, js/postpage.js, pages/postpage.html
postpage js / api 구현 거의 완료 ( 추후 준홍님이 조금 수정하실 예정)
=> :memo: postpage-js fix

css/profile.css, js/profile.js
1. 프로필 페이지 일부 UI 변경
2. 프로필 피드에서 프로필 사진, 이름, 아이디를 클릭하면 해당 사용자의 프로필로 이동하도록 변경
=> 프로필 페이지 UI 수정 및 프로필 사진, 아이디 클릭 기능 추가

css/join.css, js/join.js, pages/joinPage.html
1. 회원가입 페이지를 변경된 util.js에 맞게 리팩토링함
2. 불필요한 코드 정리
3. 썸네일 기능 추가
=> 회원가입 페이지 리팩토링

css/join.css, css/modifyProfile.css, css/profile.css, js/join.js, js/modifyProfile.js, js/profile.js, pages/modifyProfile.html
1. 프로필 수정 페이지 구현
2. 회원가입 페이지 이미지 UI 수정 및 코드 리팩토링
3. 프로필 페이지 이미지 UI 수정 및 의미 없는 코드 삭제
=> 프로필 수정 페이지 구현

css/upload.css, images/icon-delete.svg, js/upload.js, pages/upload.html
=> :memo: upload-page js, api

css/loginEmail.css, js/login.js, pages/loginEmail.html
Fix loginPage html, css, js
이전 joinMembership 페이지에서 바뀐 joinPage로 location 수정
=> 💄 Fix loginPage html, css, js

css/modifyProduct.css, js/modifyProduct.js, js/profile.js, pages/modifyProduct.html, pages/modifyProfile.html
1. 상품 등록 및 수정 페이지 구현
2. 프로필 페이지에서 상품 수정 페이지로 넘어갈 때 쿼리 스트링에 상품 아이디를 전달하도록 변경
3. 프로필 페이지에서 이미지 속성값이 없는 피드가 들어왔을 때 피드 전체가 표시되지 않는 버그 수정
=> 상품 등록 및 수정 페이지 구현

css/chatRoom.css, js/chatroom.js, pages/chatRoom.html
채팅방 페이지 - 메뉴 버튼 누르면 모달 , 댓글 입력시 전송 버튼 활성화
=> :memo: Add chat-page js

css/chatList.css, js/chatlist.js, pages/chatList.html
채팅방 목록 : 목록 첫번째 누르면 채팅방으로 이동, 
헤더버튼들 기능 구현
=> :memo: Add chatlist-js

css/postpage.css, js/constant.js, js/postpage.js, pages/postpage.html
1. 변경된 util.js에 맞게 리팩토링
2. 댓글의 삭제 및 게시가 있을 때마다 피드의 댓글 숫자 업데이트
3. 피드의 이미지, 유저 이름, id를 클릭하면 해당 유저의 프로필로 이동하도록 함
4. 피드 및 댓글의 폭, 댓글 입력창 UI, 게시 버튼 활성화/비활성화, 댓글 프로필 사진 테두리 등 UI 수정
=> 게시글 상세 페이지 리팩토링 및 UI 수정

js/join.js
Fix joinPage's upload profileImg function
프로필 이미지 등록하지 않을 경우 기본 이미지가 등록되도록 수정
=> Fix joinPage's upload profileImg function

js/splashScreen.js, pages/splashScreen.html
Fix splashScreenPage's movePage function
스플래시 화면에서 로그인 유무에 따른 페이지 이동 기능 추가
=> Fix splashScreenPage's movePage function

css/chatList.css, css/chatRoom.css, css/error404.css, css/followList.css, css/gnb.css, css/index.css, css/join.css, css/login.css, css/loginEmail.css, css/modifyProduct.css, css/modifyProfile.css, css/postpage.css, css/profile.css, css/reset.css, css/search.css, css/splashScreen.css, css/upload.css, js/chatlist.js, js/followList.js, js/profile.js, pages/chatList.html, pages/followList.html, pages/modifyProduct.html, pages/modifyProfile.html, pages/profile.html
1. reset.css에 공통된 css 추가
2. 하단 네비게이션 바 통일 (index, search 제외)
3. 불필요한 네비게이션 바 제거
=> 전체 페이지 통합을 위한 html/css 리팩토링

css/chatList.css, css/chatRoom.css, css/followList.css, css/index.css, css/join.css, css/loginEmail.css, css/modifyProduct.css, css/modifyProfile.css, css/postpage.css, css/profile.css, css/search.css, index.html, js/index.js, js/postpage.js, js/profile.js, js/search.js, pages/search.html
1. 댓글을 방금 달았을 때 0초 전 대신 방금 전이라는 메시지가 뜨도록 변경
2. 팔로우 리스트에서 글자가 짤리는 현상 수정
3. 피드의 하트와 댓글 버튼 사이의 간격 조정 및 숫자 크기 조정
4. 게시글 상세 페이지로 이동 시 불필요한 쿼리 스트링 page=readPost를 더 이상 붙이지 않도록 변경
5. font-weight이 500인 모든 css를 600으로 변경하여 400과 구분이 되도록 변경
6. index, search 페이지의 네비게이션 바 통일
=> 몇몇 페이지에서 버그 수정 및 UI 개선

js/upload.js
글 작성시 등록한 이미지가 게시글에 반영되지 않는 버그 수정
=> 이미지 업로드 버그 수정

pages/chatList.html, pages/profile.html
=> :lipstick: nav color change fix

css/upload.css, js/profile.js, js/upload.js, pages/upload.html
1. upload.html에서 게시글 작성과 게시글 수정을 둘 다 할 수 있도록 변경
2. 사진 업로드를 최대 10장까지만 할 수 있도록 제한 설정
=> 게시글 작성 페이지 수정

js/loginEmail.js, pages/joinPage.html
loginEmailPage js 수정(유효성 검사 후 Input창 클릭 시 에러 메세지 숨기는 기능 추가)
joinPage html 주석 수정
=> Add function that hide error message 

css/postpage.css, css/profile.css, css/upload.css, js/followList.js, js/index.js, js/join.js, js/modifyProfile.js, js/postpage.js, js/profile.js, js/upload.js, js/util.js, pages/followList.html, pages/upload.html
1. 팔로워/팔로잉 목록 페이지에서 헤더 제목이 팔로워/팔로잉에 맞게 표시되지 않는 버그 수정
2. util.js의 getFormattedPrice 리팩토링
3. 프로필 페이지의 상품 목록과 게시글 업로드 페이지의 이미지들의 UI 변경
4. 게시글 상세 페이지에서 게시글 메뉴 모달이 제대로 표시되지 않는 버그 수정
5. 게시글 상세 페이지에서 TypeError가 발생하는 버그 수정
6. 프로필 페이지의 피드 목록과 앨범의 사진을 클릭하면 해당 게시글 상세 페이지로 이동하도록 변경
7. 프로필 페이지에서 앨범을 선택한 후 다른 페이지에 갔다가 뒤로 가기 버튼으로 프로필 페이지로 돌아왔을 때, 피드 목록이 아닌 앨범을 표시하도록 변경
8. 게시글 상세 페이지의 댓글 textarea의 placeholder UI 변경
9. 바뀐 API 명세에 따른 변경
=> 버그 수정 및 리팩토링

js/constant.js, js/index.js
1. API 주소 변경
2. index.js에서 불러올 피드의 개수가 10개 미만이고 가장 아래의 피드가 화면에 들어왔을 때, 피드가 하나도 없는 것으로 인식하는 버그 수정
=> API 주소 변경에 따른 수정 및 index.js 버그 수정
